### ISSUE TITLE
Crash to desktop after 20~ minutes with no log msg

### ISSUE THREAD

**Issue by MegaphoneCA** [xpnteam/xpnet#11] opened 2018-11-08 23:54 UTC
Hello, using your interface and I have run into a problem. I have a flight loop hook that is executed every 60 seconds and uses RestSharp to post some data to a webserver. The crash is happening without any indication in the XPNet log or the XPlane Log.txt in the main directory. I am certain it is my plugin causing the crash but there is no indication anywhere this is the case.

I am mostly opening this issue to ask for some insight / suggestions as to what approach to take regarding this. Is it possible I am causing an Exception somewhere that is crashing X-Plane? I have wrapped basically everything I can within a try catch block but it's still doing it every time.

Here are some of the log files in question (although they don't contain much).
[XPNet Log # 1](https://github.com/MegaphoneCA/XHauler/files/2563685/xpnet.log)
[X-Plane 11 Log.txt](https://github.com/MegaphoneCA/XHauler/files/2563684/Log.txt)

Memory / CPU usage appears normal as well, really kind of stumped with this one!

**Comment by MegaphoneCA** [comment] 2018-11-09 00:49
Just reproduced this again on my system this time, again with no indication in the logs
[Log.txt](https://github.com/jaurenq/XPNet/files/2564174/Log.txt)
[xpnet.log](https://github.com/jaurenq/XPNet/files/2564175/xpnet.log)

**Comment by jaurenq** [comment] 2018-11-11 17:12
Hi Megaphone!  Couple thoughts:

If you're getting a hard crash (whole application goes away), then the chances are that the problem is somewhere either in the framework itself (unlikely) or in the native portion of XPNet (more likely).  XPNet is new enough that the best assumption for a hard crash is that there's a problem in the C++/native portions of XPNet than in your own plugin.  Especially if there's nothing in the logs - a .NET exception _should_ end up in those logs, unless I've missed some place that one can get through (possible).

I did a bit of googling on that warning and it looks like it's coming from gdb.  It might and might not be relevant to the actual crash - but I'd say it's probably saying more about gdb's ability to get a good stack trace than about the crash itself.  (Because if there were actually a 32/64-bit mismatch, the code just wouldn't run at all, instead of running for 20 minutes then crashing).

Using the XPNet Nuget build is the recommended way to use it, and I doubt using the Nuget build would in any way be _causing_ this crash, but since we're looking at a hard crash, you'll probably have to build XPNet from source in order to proceed.  If I were attacking this issue, my next step would be to download and build the XPNet source as a Debug build and run X-Plane with those binaries, attach Visual Studio (or gdb or whatever; but I know Visual Studio will work and have more experience with it), wait for the crash, and cross my fingers that the crash will end up pointing to a particular line in XPNet that can tell us something about the problem.

**Comment by jaurenq** [comment] 2018-11-21 18:42
Checking in: any word on this?

Side note: the newest release automates the deployment process.  Follow the updated instructions in the README to start a new project from the latest template (v0.1.5 or higher) and copy your source code into the new project to get a build and deployment process that will handle creating the correct Plugin directory automatically (including downloading the .NET shared runtime to the right location automatically).

**Comment by MegaphoneCA** [comment] 2018-11-21 19:01
Hello, I think if I can recall I tried building from source and it had the same effect. To be honest I ended up going with C++

**Comment by jaurenq** [comment] 2018-11-21 22:21
Ok, fair enough.  Before I close this, if you happen to have a moment to send me the plugin that you were able to recreate the problem with, I'd like to take a crack at fixing it myself -- even if you're not using XPNet, if there's a crash in it I'd like to try fixing it for the other users.  Thanks!

**Comment by MegaphoneCA** [comment] 2018-11-21 22:38
Okay I will PM you the code, do not have a .dll version of it anymore, but you can probably recreate it from my code with just doing a simeple /GET on google or something like that.

**Closed** 2019-04-11 22:50 UTC
